services:
  pytorch-gpu:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: pytorch_gpu_image
    container_name: pytorch-gpu
    #When using a GPU (Docker Compose v2 or later)
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./src:/workspace
      - ./notebooks:/notebooks  # Mount the current host directory into the container
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --port=8888 --NotebookApp.notebook_dir=/notebooks


